- hosts: servers
  roles:
     - role: ansible-role-docker
       become: yes
       tags: docker
       vars:
         - docker_install_compose: false
         - docker_edition: ce
         - docker_apt_release_channel: stable
         # A list of users who will be added to the docker group.
         - docker_users: [azureuser]
       
     - role: ansible-role-azure-devops-agent
#       become: yes 
       tags: devops-agent
       vars:
        - az_devops_agent_role: build
        - az_devops_accountname: glowfs
        - az_devops_accesstoken: test_token
        - az_devops_agent_pool_name: GlowMainBuildAgent
        - az_devops_agent_version: 2.200.2

     - role: ansible-ics-ans-role-java 
       become: yes
       become_user: root      
       tags: java-open-jdk11
       
     - role: ansible-role-nodejs 
       become: yes
       become_user: root      
       tags: npm       


      